# palette-gensho.sh -- generated by gen-theme-palette; do not edit.
#
# Source: gensho-theme (gensho-export-palette 'hex-list, gensho-palette).  Regenerate with:
#   gen-theme-palette gensho

typeset -ga _THEME_ANSI_DARK=(
  181919  #  0
  d4647f  #  1
  59965e  #  2
  a2835a  #  3
  638cb4  #  4
  cb63ae  #  5
  5f9196  #  6
  767a7a  #  7
  353737  #  8
  bb785a  #  9
  444747  # 10
  545757  # 11
  656868  # 12
  9a79c9  # 13
  5f9196  # 14
  888c8c  # 15
)

typeset -gA _THEME_SEM_DARK=(
  mono0    181919
  mono1    262828
  dim0     2a2c2c
  dim1     2f3030
  mono2    353737
  mono3    444747
  mono4    545757
  mono5    656868
  mono6    767a7a
  mono7    888c8c
  red      d4647f
  orange   bb785a
  yellow   a2835a
  green    59965e
  cyan     5f9196
  blue     638cb4
  purple   9a79c9
  magenta  cb63ae
)

typeset -ga _THEME_ANSI_LIGHT=(
  2c2e2e  #  0
  d4647f  #  1
  59965e  #  2
  a2835a  #  3
  638cb4  #  4
  cb63ae  #  5
  5f9196  #  6
  8f9394  #  7
  4b4e4e  #  8
  bb785a  #  9
  5c5e5f  # 10
  6c7070  # 11
  7e8182  # 12
  9a79c9  # 13
  5f9196  # 14
  a2a6a7  # 15
)

typeset -gA _THEME_SEM_LIGHT=(
  mono0    2c2e2e
  mono1    3c3d3e
  dim0     404242
  dim1     444747
  mono2    4b4e4e
  mono3    5c5e5f
  mono4    6c7070
  mono5    7e8182
  mono6    8f9394
  mono7    a2a6a7
  red      d4647f
  orange   bb785a
  yellow   a2835a
  green    59965e
  cyan     5f9196
  blue     638cb4
  purple   9a79c9
  magenta  cb63ae
)
