;;; my-ui-char.el --- character width settings -*- lexical-binding: t; -*-

;;; Commentary:
;; Align char-width with whatever actually decides the column count, which
;; differs by environment:
;;
;; - In a GUI, Emacs draws the glyphs itself, so char-width is matched to the
;;   glyph advances of the default font in use (font specific).  Each font gets
;;   its own (when (equal family "...") ...) block; add new fonts there.
;;
;; - In a terminal, the terminal emulator counts columns via wcwidth
;;   (ambiguous-narrow), so ambiguous characters are set to width 1 (font
;;   independent; matches Ghostty / mintty Charwidth=ambig-narrow / tmux).
;;
;; The font-specific char-width data (the defconsts below) is regenerated by
;; local/bin/gen-plemoljp-char-width (it replaces the text between the markers).

;;; Code:

;; ---- Auto-generated data (between markers) ---------------------------------

;; >>> AUTO-GENERATED gui map: char-width == PlemolJPNF-Regular.ttf glyph advance (half=528). >>>
(defconst my/plemoljp-gui-char-width-ranges
  '((#x00A1 #x00A3 1) (#x00A4 #x00A4 2) (#x00A9 #x00A9 2) (#x00AA #x00AA 1) (#x00AD #x00AE 1)
    (#x00AF #x00AF 2) (#x00B0 #x00B0 1) (#x00B2 #x00B3 1) (#x00B5 #x00B5 2) (#x00B9 #x00BA 1)
    (#x00BC #x00BF 1) (#x00C6 #x00C6 1) (#x00D0 #x00D0 1) (#x00D8 #x00D8 1) (#x00E0 #x00E1 1)
    (#x00E6 #x00E6 1) (#x00E8 #x00EA 1) (#x00EC #x00ED 1) (#x00F0 #x00F0 1) (#x00F2 #x00F3 1)
    (#x00F8 #x00FA 1) (#x00FC #x00FC 1) (#x00FE #x00FE 1) (#x0101 #x0101 1) (#x0111 #x0111 1)
    (#x0113 #x0113 1) (#x011B #x011B 1) (#x0126 #x0127 1) (#x012B #x012B 1) (#x0131 #x0133 1)
    (#x0138 #x0138 1) (#x013F #x0142 1) (#x0144 #x0144 1) (#x0148 #x014B 1) (#x014D #x014D 1)
    (#x0152 #x0153 1) (#x0166 #x0167 1) (#x016B #x016B 1) (#x01CE #x01CE 1) (#x01D0 #x01D0 1)
    (#x01D2 #x01D2 1) (#x01D4 #x01D4 1) (#x01D6 #x01D6 1) (#x01D8 #x01D8 1) (#x01DA #x01DA 1)
    (#x01DC #x01DC 1) (#x025A #x025C 2) (#x025E #x025E 2) (#x0260 #x0260 2) (#x0262 #x0267 2)
    (#x026E #x0276 2) (#x0278 #x0278 2) (#x0282 #x0282 2) (#x0289 #x028E 2) (#x0290 #x0292 2)
    (#x0298 #x0298 2) (#x029C #x029C 2) (#x02B7 #x02B7 2) (#x02C7 #x02C7 1) (#x02C8 #x02C8 2)
    (#x02CC #x02CC 2) (#x02D0 #x02D0 1) (#x02D1 #x02D1 2) (#x02D8 #x02DB 1) (#x02DD #x02DD 1)
    (#x02DE #x02DE 2) (#x02E5 #x02E9 2) (#x0305 #x0305 1) (#x0384 #x0386 2) (#x0388 #x0389 2)
    (#x038C #x038C 2) (#x038E #x038F 2) (#x0399 #x0399 1) (#x03AB #x03AE 2) (#x03B0 #x03B0 2)
    (#x03B6 #x03B6 1) (#x03B9 #x03B9 1) (#x03BE #x03BE 1) (#x03C0 #x03C0 1) (#x03C2 #x03C2 2)
    (#x03CB #x03CE 2) (#x03D0 #x03D1 2) (#x03D5 #x03D5 2) (#x03DB #x03DB 2) (#x0433 #x0433 1)
    (#x0442 #x0442 1) (#x1E3E #x1E3F 2) (#x1F70 #x1F73 2) (#x2012 #x2012 2) (#x2022 #x2022 1)
    (#x2024 #x2024 1) (#x2027 #x2027 1) (#x2032 #x2033 1) (#x2035 #x2035 1) (#x203C #x203C 2)
    (#x203E #x203E 1) (#x203F #x203F 2) (#x2042 #x2042 2) (#x2047 #x2049 2) (#x2051 #x2051 2)
    (#x205A #x205A 2) (#x205D #x205D 2) (#x2074 #x2074 1) (#x2081 #x2084 1) (#x20AC #x20AC 1)
    (#x2100 #x2100 2) (#x210A #x210A 2) (#x210F #x210F 2) (#x2126 #x2126 1) (#x2127 #x2127 2)
    (#x2135 #x2135 2) (#x213B #x213B 2) (#x2152 #x2152 2) (#x2153 #x2154 1) (#x215B #x215E 1)
    (#x217A #x217B 2) (#x217F #x217F 2) (#x2194 #x2199 1) (#x21B8 #x21B9 1) (#x21C4 #x21C6 2)
    (#x21CB #x21CC 2) (#x21D0 #x21D0 2) (#x21E6 #x21E6 2) (#x21E8 #x21E9 2) (#x21F5 #x21F5 2)
    (#x2205 #x2205 2) (#x2209 #x2209 2) (#x220F #x220F 1) (#x2212 #x2212 1) (#x2213 #x2213 2)
    (#x2215 #x2215 1) (#x2223 #x2223 1) (#x2226 #x2226 2) (#x222B #x222B 1) (#x222D #x222D 2)
    (#x222E #x222E 1) (#x2236 #x2237 1) (#x223C #x223C 1) (#x2243 #x2243 2) (#x2245 #x2245 2)
    (#x2248 #x2248 1) (#x224C #x224C 1) (#x2262 #x2262 2) (#x2264 #x2265 1) (#x226E #x226F 1)
    (#x2272 #x2273 2) (#x2276 #x2277 2) (#x2284 #x2285 2) (#x228A #x228B 2) (#x2296 #x2298 2)
    (#x2299 #x2299 1) (#x229E #x229E 2) (#x22A0 #x22A0 2) (#x22DA #x22DB 2) (#x2305 #x2307 2)
    (#x2318 #x2318 2) (#x239B #x239E 2) (#x23A0 #x23A1 2) (#x23A3 #x23A4 2) (#x23A6 #x23A9 2)
    (#x23AB #x23AD 2) (#x23B0 #x23B1 2) (#x23BE #x23CC 2) (#x23CE #x23CE 2) (#x2423 #x2423 2)
    (#x24EA #x24EA 2) (#x2580 #x258F 1) (#x2592 #x2595 1) (#x25A2 #x25A2 2) (#x25A3 #x25A9 1)
    (#x25AA #x25AB 2) (#x25B1 #x25B1 2) (#x25C8 #x25C8 1) (#x25C9 #x25C9 2) (#x25CC #x25CC 2)
    (#x25D2 #x25D3 2) (#x25E6 #x25E6 2) (#x25FD #x25FE 1) (#x2600 #x2603 2) (#x2616 #x2617 2)
    (#x261D #x261D 2) (#x261F #x261F 2) (#x2662 #x2662 2) (#x2666 #x2666 2) (#x2669 #x2669 1)
    (#x266B #x266B 2) (#x266E #x266E 2) (#x2672 #x267D 2) (#x26A0 #x26A0 2) (#x2702 #x2702 2)
    (#x271A #x271A 2) (#x273F #x2740 2) (#x2756 #x2756 2) (#x27A1 #x27A1 2) (#x2934 #x2935 2)
    (#x29BF #x29BF 2) (#x29FA #x29FB 2) (#x2B05 #x2B07 2) (#x2B95 #x2B95 2))
  "GUI correction runs (LO HI WIDTH): char-width == PlemolJP NF glyph advance.
Box-drawing U+2500-257F is excluded (handled as a half-width exception).")
;; <<< END gui map <<<

;; >>> AUTO-GENERATED ambig-narrow map: wcwidth ambig-narrow (East-Asian ambiguous -> 1, combining -> 0). >>>
(defconst my/char-width-ambig-narrow-ranges
  '((#x00A1 #x00A3 1) (#x00A7 #x00A8 1) (#x00AA #x00AA 1) (#x00AC #x00AE 1) (#x00B0 #x00B4 1)
    (#x00B6 #x00B6 1) (#x00B8 #x00BA 1) (#x00BC #x00BF 1) (#x00C6 #x00C6 1) (#x00D0 #x00D0 1)
    (#x00D7 #x00D8 1) (#x00E0 #x00E1 1) (#x00E6 #x00E6 1) (#x00E8 #x00EA 1) (#x00EC #x00ED 1)
    (#x00F0 #x00F0 1) (#x00F2 #x00F3 1) (#x00F7 #x00FA 1) (#x00FC #x00FC 1) (#x00FE #x00FE 1)
    (#x0101 #x0101 1) (#x0111 #x0111 1) (#x0113 #x0113 1) (#x011B #x011B 1) (#x0126 #x0127 1)
    (#x012B #x012B 1) (#x0131 #x0133 1) (#x0138 #x0138 1) (#x013F #x0142 1) (#x0144 #x0144 1)
    (#x0148 #x014B 1) (#x014D #x014D 1) (#x0152 #x0153 1) (#x0166 #x0167 1) (#x016B #x016B 1)
    (#x01CE #x01CE 1) (#x01D0 #x01D0 1) (#x01D2 #x01D2 1) (#x01D4 #x01D4 1) (#x01D6 #x01D6 1)
    (#x01D8 #x01D8 1) (#x01DA #x01DA 1) (#x01DC #x01DC 1) (#x0251 #x0251 1) (#x0261 #x0261 1)
    (#x02C4 #x02C4 1) (#x02C7 #x02C7 1) (#x02C9 #x02CB 1) (#x02CD #x02CD 1) (#x02D0 #x02D0 1)
    (#x02D8 #x02DB 1) (#x02DD #x02DD 1) (#x02DF #x02DF 1) (#x0300 #x036F 0) (#x0391 #x03A1 1)
    (#x03A3 #x03A9 1) (#x03B1 #x03C1 1) (#x03C3 #x03C9 1) (#x0401 #x0401 1) (#x0410 #x044F 1)
    (#x0451 #x0451 1) (#x2010 #x2010 1) (#x2013 #x2016 1) (#x2018 #x2019 1) (#x201C #x201D 1)
    (#x2020 #x2022 1) (#x2024 #x2027 1) (#x2030 #x2030 1) (#x2032 #x2033 1) (#x2035 #x2035 1)
    (#x203B #x203B 1) (#x203E #x203E 1) (#x2074 #x2074 1) (#x207F #x207F 1) (#x2081 #x2084 1)
    (#x20AC #x20AC 1) (#x2103 #x2103 1) (#x2105 #x2105 1) (#x2109 #x2109 1) (#x2113 #x2113 1)
    (#x2116 #x2116 1) (#x2121 #x2122 1) (#x2126 #x2126 1) (#x212B #x212B 1) (#x2153 #x2154 1)
    (#x215B #x215E 1) (#x2160 #x216B 1) (#x2170 #x2179 1) (#x2189 #x2189 1) (#x2190 #x2199 1)
    (#x21B8 #x21B9 1) (#x21D2 #x21D2 1) (#x21D4 #x21D4 1) (#x21E7 #x21E7 1) (#x2200 #x2200 1)
    (#x2202 #x2203 1) (#x2207 #x2208 1) (#x220B #x220B 1) (#x220F #x220F 1) (#x2211 #x2212 1)
    (#x2215 #x2215 1) (#x221A #x221A 1) (#x221D #x2220 1) (#x2223 #x2223 1) (#x2225 #x2225 1)
    (#x2227 #x222C 1) (#x222E #x222E 1) (#x2234 #x2237 1) (#x223C #x223D 1) (#x2248 #x2248 1)
    (#x224C #x224C 1) (#x2252 #x2252 1) (#x2260 #x2261 1) (#x2264 #x2267 1) (#x226A #x226B 1)
    (#x226E #x226F 1) (#x2282 #x2283 1) (#x2286 #x2287 1) (#x2295 #x2295 1) (#x2299 #x2299 1)
    (#x22A5 #x22A5 1) (#x22BF #x22BF 1) (#x2312 #x2312 1) (#x2460 #x24E9 1) (#x24EB #x254B 1)
    (#x2550 #x2573 1) (#x2580 #x258F 1) (#x2592 #x2595 1) (#x25A0 #x25A1 1) (#x25A3 #x25A9 1)
    (#x25B2 #x25B3 1) (#x25B6 #x25B7 1) (#x25BC #x25BD 1) (#x25C0 #x25C1 1) (#x25C6 #x25C8 1)
    (#x25CB #x25CB 1) (#x25CE #x25D1 1) (#x25E2 #x25E5 1) (#x25EF #x25EF 1) (#x2605 #x2606 1)
    (#x260E #x260F 1) (#x261C #x261C 1) (#x261E #x261E 1) (#x2640 #x2640 1) (#x2642 #x2642 1)
    (#x2660 #x2661 1) (#x2663 #x2665 1) (#x2667 #x266A 1) (#x266C #x266D 1) (#x266F #x266F 1)
    (#x269E #x269F 1) (#x26BF #x26BF 1) (#x26C6 #x26CD 1) (#x26CF #x26D3 1) (#x26D5 #x26E1 1)
    (#x26E3 #x26E3 1) (#x26E8 #x26E9 1) (#x26EB #x26F1 1) (#x26F4 #x26F4 1) (#x26F6 #x26F9 1)
    (#x26FB #x26FC 1) (#x26FE #x26FF 1) (#x273D #x273D 1) (#x2776 #x277F 1) (#x2B56 #x2B59 1))
  "TTY correction runs (LO HI WIDTH): wcwidth ambiguous-narrow.
Ambiguous -> 1, combining -> 0.  Font independent (matches the terminal).")
;; <<< END ambig-narrow map <<<

;; ---- Apply -----------------------------------------------------------------

(defun my/char-width-apply-ranges (ranges)
  "Apply RANGES (list of (LO HI WIDTH)) to `char-width-table'."
  (pcase-dolist (`(,lo ,hi ,w) ranges)
    (set-char-table-range char-width-table (cons lo hi) w)))

(defun my/char-width-setup (&optional frame)
  "Match `char-width-table' to how FRAME actually counts columns.
GUI uses the default font's glyph advances; a terminal uses wcwidth
ambiguous-narrow.  The default font is only settled after my-ui-face applies
it, so this runs from `after-init-hook' / `after-make-frame-functions'."
  (if (display-graphic-p frame)
      ;; GUI: font-specific correction; add a when-block per extra font.
      (let ((family (and (boundp 'my/font-default) (plist-get my/font-default :family))))
        (when (equal family "PlemolJP NF")
          (my/char-width-apply-ranges my/plemoljp-gui-char-width-ranges)
          ;; Box-drawing U+2500-257F is baked half-width into our PlemolJP NF
          ;; build (Console NF glyphs merged in via local/bin/build-plemoljp-nf),
          ;; so set char-width to 1 to match.  We cannot reroute it with
          ;; set-fontset-font here: on macOS the face's own :family covers
          ;; box-drawing and wins over the fallback fontset.
          (set-char-table-range char-width-table (cons #x2500 #x257F) 1)))
    ;; TTY: terminal counts by wcwidth ambiguous-narrow (font independent).
    (my/char-width-apply-ranges my/char-width-ambig-narrow-ranges)))

(add-hook 'after-init-hook #'my/char-width-setup)
(add-hook 'after-make-frame-functions #'my/char-width-setup)

(provide 'my-ui-char)
;;; my-ui-char.el ends here
